/* tslint:disable */
/**
 * TocaDoCartuchoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapitools/openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
export type {
  AdvertisementDTO,
  AdvertisementImageDTO,
  SaleDTO,
  TradeDTO,
  GameDTO,
  CartridgeTypeDTO,
  PreservationStateDTO,
  GameLocalizationDTO,
  RegionDTO,
  GenreDTO,
  ThemeDTO,
  LanguageSupportDTO,
  UserDTO,
  UserAddressDTO,
  AddressDTO,
  UserProfileImageDTO,
  CustomLoginRequest,
  CustomRegisterRequest,
  UserForUpdateDTO,
  UserAddressForUpdateDTO,
  AddressForCreationDTO,
  CustomUserForUpdateDTO,
  CustomInfoRequest,
} from "./types";

